name: 'Upload to S3'
description: ''
inputs:

  dirname:
    description: 'folder to upload'
    required: false
    default: s3
     
  bucketname:
    description: 'Bucket name'
    requred: true
    default: 'web-bundles'

  s3dirname:
    description: 'folder on S3 to upload to'
    requred: false
    default: ''
        
  AWS_ACCESS_KEY_ID_SELECTEL:
    required: true
    default: 'null'

  AWS_SECRET_ACCESS_KEY_SELECTEL:
    required: true
    default: 'null'

  ENDPOINT:
    required: false
    default: https://s3.selcdn.ru

  SELECTEL_URL:
    required: false
    default: ''

runs:
  using: "composite"
  steps: 
    - name: Configure Selectel
      shell: bash
      run: |
        aws configure set aws_access_key_id "145478_Jnqa"
        aws configure set aws_secret_access_key "4(7-jn/UBd" 
        aws configure set endpoint-url https://s3.selcdn.ru/
        aws configure set default.region "ru-1"
        aws s3 ls --endpoint https://s3.selcdn.ru/


    - name: Upload to Selectel
      shell: bash
      run: |
        aws s3 cp ${{ inputs.dirname }} 's3://${{ inputs.bucketname }}/${{ inputs.subfolder }}' --recursive --endpoint ${{ inputs.ENDPOINT }}


    - name: configuring AMAZON profile 
      shell: bash
      run: |
        aws configure set aws_access_key_id "${{ inputs.AWS_ACCESS_KEY_ID }}"
        aws configure set aws_secret_access_key "${{ inputs.AWS_SECRET_ACCESS_KEY }}"
        aws configure set default.region "${{ inputs.AWS_REGION }}"
        aws configure set endpoint-url s3.${{ inputs.AWS_REGION }}.amazonaws.com
        aws s3 ls || echo "SELECTEL: Bad credentials"


    - name: Print URLs 
      shell: bash
      run: |
        echo later
