name: 'Upload to S3'
description: ''
inputs:

  dirname:
    description: 'folder to upload'
    required: false
    default: s3
     
  bucketname:
    description: 'Bucket name'
    requred: true
    default: 'web-bundles'

  s3dirname:
    description: 'folder on S3 to upload to'
    requred: false
    default: ''
        
  AWS_ACCESS_KEY_ID_SELECTEL:
    required: true

  AWS_SECRET_ACCESS_KEY_SELECTEL:
    required: true

  ENDPOINT:
    required: false
    default: https://s3.selcdn.ru

  SELECTEL_URL:
    required: false
    default: ''

runs:
  using: "composite"
  steps: 
    - name: Configure Selectel
      shell: bash
      run: |
        aws configure set aws_access_key_id "${{ inputs.AWS_ACCESS_KEY_ID_SELECTEL }}"
        aws configure set aws_secret_access_key "${{ inputs.AWS_SECRET_ACCESS_KEY_SELECTEL }}" 
        aws configure set endpoint-url ${{ inputs.ENDPOINT }}
        aws configure set default.region "ru-1"
        aws s3 ls --endpoint https://s3.selcdn.ru/


    # - name: Upload to Selectel
    #   shell: bash
    #   run: |
    #     aws s3 cp ${{ inputs.dirname }} 's3://${{ inputs.bucketname }}/${{ inputs.subfolder }}' --recursive --endpoint ${{ inputs.ENDPOINT }}

    - name: Sync with Selectel
      shell: bash
      run: |
        aws s3 sync ${{ inputs.dirname }} 's3://${{ inputs.bucketname }}/${{ inputs.s3dirname }}' --endpoint ${{ inputs.ENDPOINT }}

    - name: Print URLs 
      shell: bash
      run: |
        echo later
