name: 'Upload dir & zip to S3'
description: ''
inputs:

  dirname:
    description: 'folder to upload'
    required: false
    default: s3
    
  archivename:
    requred: false
    description: 'Archive name'
    default: 'null'

  version:
    description: 'Version'
    requred: true
  
  bucketname:
    description: 'Bucket name'
    requred: true
    default: 'web-bundles'

  bundlename:
    description: 'Package/bundle name'
    requred: true
    
  removeAfterUpload:
    required: false
    default: false
    
  subfolder:
    required: false
    default: 'null'
    
  AWS_ACCESS_KEY_ID:
    required: true
  AWS_SECRET_ACCESS_KEY:
    required: true
  AWS_REGION:
    required: false
    default: 'us-east-2'
        
  AWS_ACCESS_KEY_ID_SELECTEL:
    required: false
    default: 'null'
  AWS_SECRET_ACCESS_KEY_SELECTEL:
    required: false
    default: 'null'
  ENDPOINT:
    required: false
    default: 'https://s3.selcdn.ru' # --endpoint-url=
  SELECTEL_URL:
    required: false
    default: ''

runs:
  using: "composite"
  steps: 
    - name: Prepend subfolder with slashes
      shell: bash
      run: |
        [[ ${{ inputs.subfolder }} != 'null' ]] &&\
        echo "BUNDLENAME=${{ inputs.bundlename }}/${{ inputs.subfolder }}" >> $GITHUB_ENV ||\
        echo "BUNDLENAME=${{ inputs.bundlename }}" >> $GITHUB_ENV
        echo ${{env.BUNDLENAME}}
    - name: Prepare awscliv2 for the next steps
      shell: bash
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip > /dev/null
        sudo ./aws/install > /dev/null
   
    - name: configuring SELECTEL profile
      shell: bash
      run: |
        echo "conf S"
        aws configure set aws_access_key_id ${{ inputs.AWS_ACCESS_KEY_ID }} --profile SELECTEL
        aws configure set aws_secret_access_key ${{ inputs.AWS_SECRET_ACCESS_KEY }} --profile SELECTEL
        aws configure set default.region ru-1a --profile SELECTEL
        aws configure set endpoint-url ${{ inputs.ENDPOINT }} --profile SELECTEL
    
    - name: configuring AMAZON profile
      shell: bash
      run: |
        echo "conf A"
        aws configure set aws_access_key_id ${{ inputs.AWS_ACCESS_KEY_ID }} --profile AMAZON
        aws configure set aws_secret_access_key ${{ inputs.AWS_SECRET_ACCESS_KEY }} --profile AMAZON
        aws configure set default.region ${{ inputs.AWS_REGION }} --profile AMAZON
    
    - name: Upload to S3
      shell: bash
      run: |
        echo "UPLOAD"
        echo ${{env.BUNDLENAME}}
        [[ "${{ inputs.archivename }}" != "null" ]] &&\
        (aws s3 cp ./${{ inputs.dirname }}/${{ inputs.archivename }}\
         s3://${{ inputs.bucketname }}/bundles/${{env.BUNDLENAME}}/${{ inputs.version }}/${{ inputs.version }}.zip --profile AMAZON ||\
        echo "no ./${{ inputs.dirname }}/${{ inputs.archivename }}" && echo exit 1)
        echo "AMAZON Uploaded: s3://${{ inputs.bucketname }}/bundles/${{env.BUNDLENAME}}/${{ inputs.version }}/${{ inputs.version }}.zip"
        [[ "${{ inputs.archivename }}" != "null" ]] &&\
        [[ "${{ inputs.AWS_ACCESS_KEY_ID_SELECTEL }}" != "null" ]] &&\
        [[ "${{ inputs.AWS_SECRET_ACCESS_KEY_SELECTEL }}" != "null" ]] &&\
        (aws s3 cp ./${{ inputs.dirname }}/${{ inputs.archivename }}\
         s3://${{ inputs.bucketname }}/bundles/${{env.BUNDLENAME}}/${{ inputs.version }}/${{ inputs.version }}.zip --profile SELECTEL ||\
        echo "no ./${{ inputs.dirname }}/${{ inputs.archivename }}" && echo exit 1)
        echo "SELECTEL Uploaded: s3://${{ inputs.bucketname }}/bundles/${{env.BUNDLENAME}}/${{ inputs.version }}/${{ inputs.version }}.zip"
        aws s3 cp ./${{ inputs.dirname }}/ s3://${{ inputs.bucketname }}/bundles/${{env.BUNDLENAME}}/${{ inputs.version }}/ --recursive --include "*" --exclude "${{ inputs.archivename }} --profile AMAZON" 
        echo "AMAZON Uploaded: s3://${{ inputs.bucketname }}/bundles/${{env.BUNDLENAME}}/${{ inputs.version }}/ --recursive --include "*" --exclude "${{ inputs.archivename }}"
        [[ "${{ inputs.AWS_ACCESS_KEY_ID_SELECTEL }}" != "null" ]] &&\
        [[ "${{ inputs.AWS_SECRET_ACCESS_KEY_SELECTEL }}" != "null" ]] &&\
        aws s3 cp ./${{ inputs.dirname }}/ s3://${{ inputs.bucketname }}/bundles/${{env.BUNDLENAME}}/${{ inputs.version }}/ --recursive --include "*" --exclude "${{ inputs.archivename }} --profile SELECTEL" 
        echo "SELECTEL Uploaded: s3://${{ inputs.bucketname }}/bundles/${{env.BUNDLENAME}}/${{ inputs.version }}/ --recursive --include "*" --exclude "${{ inputs.archivename }}"
        echo 'Complete!'
      
    - name: Print URLs 
      shell: bash
      run: |
        echo "${{ inputs.SELECTEL_URL }}/${{ inputs.bucketname }}/bundles/${{ inputs.bundlename }}/${{ inputs.version }}/index.html"
        echo "${{ inputs.SELECTEL_URL }}/${{ inputs.bucketname }}/bundles/${{ inputs.bundlename }}/${{ inputs.version }}.zip"
        echo " - - - "
        echo "https://${{ inputs.bucketname }}.s3.${{ inputs.AWS_REGION }}.amazonaws.com/${{ inputs.bucketname }}/bundles/${{ inputs.bundlename }}/${{ inputs.version }}/index.html"
        echo "https://${{ inputs.bucketname }}.s3.${{ inputs.AWS_REGION }}.amazonaws.com/${{ inputs.bucketname }}/bundles/${{ inputs.bundlename }}/${{ inputs.version }}.zip"

