
name: Upload to Selectel

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Upload archive to S3
        uses: Jnqa/zebruzka@main
        with:
          dirname: lab
          bucketname: jnqa-test #wiz417-bucket #web-bundles 
          # s3dirname: lab_on_cloud
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_SELECTEL }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_SELECTEL }}
          # ENDPOINT: https://s3.selcdn.ru
          # SELECTEL_URL: https://6a39d29f-7919-4a2c-b54e-f8066f9effbb.selcdn.net--no
